/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skp_report;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Random;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author chareq
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        autor = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        raport1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tytul = new javax.swing.JLabel();
        raport2 = new javax.swing.JButton();
        raport3 = new javax.swing.JButton();
        raport4 = new javax.swing.JButton();
        raport5 = new javax.swing.JButton();
        raport6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Raporty dla bazy SKP");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        autor.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        autor.setText("Kacper Owczarek");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        date.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        date.setText("© 2023");

        raport1.setBackground(new java.awt.Color(54, 88, 150));
        raport1.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        raport1.setForeground(new java.awt.Color(255, 255, 255));
        raport1.setText("Formularz do wypełnienia podczas badania");
        raport1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raport1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raport1MouseExited(evt);
            }
        });
        raport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raport1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(54, 88, 150));

        tytul.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        tytul.setForeground(new java.awt.Color(255, 255, 255));
        tytul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytul.setText("SYSTEM RAPORTOWANIA DLA BAZY SKP");
        tytul.setAlignmentY(0.0F);
        tytul.setMaximumSize(new java.awt.Dimension(340, 35));
        tytul.setMinimumSize(new java.awt.Dimension(340, 35));
        tytul.setPreferredSize(new java.awt.Dimension(350, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        raport2.setBackground(new java.awt.Color(54, 88, 150));
        raport2.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        raport2.setForeground(new java.awt.Color(255, 255, 255));
        raport2.setText("Wykaz klientów w bazie SKP");
        raport2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raport2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raport2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raport2MouseExited(evt);
            }
        });
        raport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raport2ActionPerformed(evt);
            }
        });

        raport3.setBackground(new java.awt.Color(54, 88, 150));
        raport3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        raport3.setForeground(new java.awt.Color(255, 255, 255));
        raport3.setText("Podsumowanie informacji ze wszystkich stacji danego właściciela");
        raport3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raport3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raport3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raport3MouseExited(evt);
            }
        });
        raport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raport3ActionPerformed(evt);
            }
        });

        raport4.setBackground(new java.awt.Color(54, 88, 150));
        raport4.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        raport4.setForeground(new java.awt.Color(255, 255, 255));
        raport4.setText("Wykaz pojazdów w bazie SKP");
        raport4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raport4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raport4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raport4MouseExited(evt);
            }
        });
        raport4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raport4ActionPerformed(evt);
            }
        });

        raport5.setBackground(new java.awt.Color(54, 88, 150));
        raport5.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        raport5.setForeground(new java.awt.Color(255, 255, 255));
        raport5.setText("Wykaz etatów na danej stacji");
        raport5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raport5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raport5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raport5MouseExited(evt);
            }
        });
        raport5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raport5ActionPerformed(evt);
            }
        });

        raport6.setBackground(new java.awt.Color(54, 88, 150));
        raport6.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        raport6.setForeground(new java.awt.Color(255, 255, 255));
        raport6.setText("Zaświadczenie o przeprowadzonym badaniu pojazdu");
        raport6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        raport6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                raport6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                raport6MouseExited(evt);
            }
        });
        raport6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raport6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(autor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date)
                .addGap(179, 179, 179)
                .addComponent(logo)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(raport3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raport2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raport4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raport5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raport6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(raport1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(150, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(raport2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(raport3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(raport4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(raport5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(raport6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autor)
                            .addComponent(date))
                        .addGap(15, 15, 15)))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(raport1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );

        raport1.setBorderPainted(false);
        raport1.setFocusPainted(false);
        raport1.setRolloverEnabled(true);
        raport2.setBorderPainted(false);
        raport2.setFocusPainted(false);
        raport2.setRolloverEnabled(true);
        raport3.setBorderPainted(false);
        raport3.setFocusPainted(false);
        raport3.setRolloverEnabled(true);
        raport4.setBorderPainted(false);
        raport4.setFocusPainted(false);
        raport4.setRolloverEnabled(true);
        raport5.setBorderPainted(false);
        raport5.setFocusPainted(false);
        raport5.setRolloverEnabled(true);
        raport6.setBorderPainted(false);
        raport6.setFocusPainted(false);
        raport6.setRolloverEnabled(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raport1ActionPerformed
        //Otworzenie okna do wypełnienia pierwszego formularza i zamknięcie głównego okna
        Raport1 rap1 = new Raport1();
        rap1.show();
        
        dispose();
    }//GEN-LAST:event_raport1ActionPerformed

    private void raport1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport1MouseEntered
        raport1.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_raport1MouseEntered

    private void raport1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport1MouseExited
        raport1.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_raport1MouseExited

    private void raport2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport2MouseEntered
        raport2.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_raport2MouseEntered

    private void raport2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport2MouseExited
        raport2.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_raport2MouseExited

    private void raport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raport2ActionPerformed
        //Otworzenie okna do wypełnienia drugiego raportu i zamknięcie głównego okna
        Raport2 rap2 = new Raport2();
        rap2.show();
        
        dispose();
    }//GEN-LAST:event_raport2ActionPerformed

    private void raport3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport3MouseEntered
        raport3.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_raport3MouseEntered

    private void raport3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport3MouseExited
        raport3.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_raport3MouseExited

    private void raport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raport3ActionPerformed
        //Otworzenie okna do wypełnienia trzeciego raportu i zamknięcie głównego okna
        Raport3 rap3 = new Raport3();
        rap3.show();
        
        dispose();
    }//GEN-LAST:event_raport3ActionPerformed

    private void raport4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport4MouseEntered
        raport4.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_raport4MouseEntered

    private void raport4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport4MouseExited
        raport4.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_raport4MouseExited

    private void raport4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raport4ActionPerformed
        //Wygenerowanie czwartego raportu bez żadnych parametrów 
        try {
            //PODANIE STEROWNIKA POŁĄCZENIA Z BAZĄ
            Class.forName("org.firebirdsql.jdbc.FBDriver");
            //SPRAWDZENIE POŁĄCZENIA Z BAZĄ
            try (Connection con = DriverManager.getConnection("jdbc:firebirdsql://localhost:3050//databases/skp.fdb", "SYSDBA", "Czarek08#")) {
                String reportPath = "/databases/Raporty/Raport4.jrxml";     //Ustawienie ścieżki do szablonu raportu
                
                //GENEROWANIE IDENTYFIKATORA (KODU) RAPORTU
                String znaki = "abcdefghijklmnopqrstuvwxyz1234567890";      //Dostępne znaki do tworzenia kodu
                StringBuilder kodID = new StringBuilder();      //Zmienna do przechowywania dynamicznego łańcucha znakowego
                Random random = new Random();       //Utworzenie obiektu generatora liczb pseudolosowych
                //Pętla służąca do dodawania losowych znaków z zakresu do identyfiktora raportu (i we wskazanych miejscach dodająca myślnik)
                for (int i = 0; i < 19; i++) {
                    if (i == 4 || i == 9 || i == 14) {
                        kodID.append("-");
                    } else {
                        kodID.append(znaki.charAt(random.nextInt(znaki.length())));
                    }
                }

                //PARAMETRY
                HashMap<String, Object> parametry = new HashMap<String, Object>();  //Utworzenie HashMapy do przechowywania paremetrów (nazwa, wartość)
                parametry.put("qrCode", "resources/qr-code.png");   //Przypisanie do parametru qrCode obrazka qr-code.png
                parametry.put("idCode", kodID.toString());  //Przypisanie do parametru idCode utworzonego identyfikatora raportu

                //Wygenerowanie raportu, uzupełnienie go i wyświetlenie w oknie JasperViewer
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                JasperPrint jp = JasperFillManager.fillReport(jr, parametry, con);
                JasperViewer.viewReport(jp, false);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_raport4ActionPerformed

    private void raport5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport5MouseEntered
        raport5.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_raport5MouseEntered

    private void raport5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport5MouseExited
        raport5.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_raport5MouseExited

    private void raport5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raport5ActionPerformed
        //Otworzenie okna do wypełnienia piątego raportu i zamknięcie głównego okna
        Raport5 rap5 = new Raport5();
        rap5.show();
        
        dispose();
    }//GEN-LAST:event_raport5ActionPerformed

    private void raport6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport6MouseEntered
        raport6.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_raport6MouseEntered

    private void raport6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raport6MouseExited
        raport6.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_raport6MouseExited

    private void raport6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raport6ActionPerformed
        //Otworzenie okna do wypełnienia szóstego formularza i zamknięcie głównego okna
        Raport6 rap6 = new Raport6();
        rap6.show();
        
        dispose();
    }//GEN-LAST:event_raport6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autor;
    private javax.swing.JLabel date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton raport1;
    private javax.swing.JButton raport2;
    private javax.swing.JButton raport3;
    private javax.swing.JButton raport4;
    private javax.swing.JButton raport5;
    private javax.swing.JButton raport6;
    private javax.swing.JLabel tytul;
    // End of variables declaration//GEN-END:variables
}
