/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package skp_report;

import java.awt.Color;
import javax.swing.border.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Random;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author chareq
 */
public class Raport6 extends javax.swing.JFrame {
    String TypB;

    /**
     * Creates new form MainWindow
     */
    public Raport6() {
        initComponents();
        overviewIdFillData();
    }
    
    //Funkcja służąca do uzupełnienia pola wyboru dla Id badania wartościami z bazy
    public void overviewIdFillData() {
        try {
            Class.forName("org.firebirdsql.jdbc.FBDriver");
            Connection con = DriverManager.getConnection("jdbc:firebirdsql://localhost:3050//databases/skp.fdb", "SYSDBA", "Czarek08#");
            java.sql.Statement stat = con.createStatement();
            String query = "SELECT Id_wlasciciela FROM Wlasciciele";
            java.sql.ResultSet rs = stat.executeQuery(query);
            
            while (rs.next()) {
                IdB.addItem(Integer.toString(rs.getInt("Id_wlasciciela")));
            }
            
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    //Funkcja służąca do sprawdzenia, czy wskazane badanie jest badaniem dodatkowym i przypisanie wybranych wartości do zmiennej globalnej TypB
    public void overviewAdditionalType(int Id_b) {
        try {
            Class.forName("org.firebirdsql.jdbc.FBDriver");
            Connection con = DriverManager.getConnection("jdbc:firebirdsql://localhost:3050//databases/skp.fdb", "SYSDBA", "Czarek08#");
            java.sql.Statement stat = con.createStatement();
            
            String query = "SELECT * FROM Dodatkowe WHERE Id_badania="+Id_b;
            java.sql.ResultSet rs = stat.executeQuery(query);
            
            while (rs.next()) {
                TypB = "Dodatkowe, "+rs.getString("Typ_testow");
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
      //Funkcja służąca do sprawdzenia, czy wskazane badanie jest badaniem okresowym i przypisanie wybranych wartości do zmiennej globalnej TypB
    public void overviewType(int Id_b) {
        try {
            Class.forName("org.firebirdsql.jdbc.FBDriver");
            Connection con = DriverManager.getConnection("jdbc:firebirdsql://localhost:3050//databases/skp.fdb", "SYSDBA", "Czarek08#");
            java.sql.Statement stat = con.createStatement();

            String query = "SELECT * FROM Okresowe WHERE Id_badania=" + Id_b;
            java.sql.ResultSet rs = stat.executeQuery(query);
            
            if(!rs.isBeforeFirst()) {
                overviewAdditionalType(Id_b);
            }
            else {
                TypB = "Okresowe";
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        autor = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tytul = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        tytul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IdB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        kraj = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Raporty dla bazy SKP");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        autor.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        autor.setText("Kacper Owczarek");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        date.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        date.setText("© 2023");

        generate.setBackground(new java.awt.Color(54, 88, 150));
        generate.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Generuj raport");
        generate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generateMouseExited(evt);
            }
        });
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(54, 88, 150));

        tytul.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        tytul.setForeground(new java.awt.Color(255, 255, 255));
        tytul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytul.setText("BADANIA TECHNICZNEGO POJAZDU");
        tytul.setAlignmentY(0.0F);
        tytul.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        tytul.setMaximumSize(new java.awt.Dimension(340, 35));
        tytul.setMinimumSize(new java.awt.Dimension(340, 35));
        tytul.setPreferredSize(new java.awt.Dimension(350, 50));

        back1.setBackground(new java.awt.Color(54, 88, 150));
        back1.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setText("<");
        back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back1.setIconTextGap(0);
        back1.setMargin(null);
        back1.setPreferredSize(new java.awt.Dimension(50, 50));
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                back1MouseExited(evt);
            }
        });
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        tytul1.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        tytul1.setForeground(new java.awt.Color(255, 255, 255));
        tytul1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytul1.setText("ZAŚWIADCZENIE O PRZEPROWADZONYM");
        tytul1.setAlignmentY(0.0F);
        tytul1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        tytul1.setMaximumSize(new java.awt.Dimension(340, 35));
        tytul1.setMinimumSize(new java.awt.Dimension(340, 35));
        tytul1.setPreferredSize(new java.awt.Dimension(350, 50));
        tytul1.setVerifyInputWhenFocusTarget(false);
        tytul1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tytul1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tytul1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        back1.setFocusPainted(false);
        back1.setRolloverEnabled(true);
        back1.setBorder(new LineBorder(Color.WHITE, 2));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel1.setText("Kraj rejestracji:");

        IdB.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        IdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel2.setText("ID badania:");

        kraj.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        kraj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "AFG", "AG", "AL", "AM", "AN", "AND", "AUS", "AZ", "B", "BD", "BDS", "BF", "BG", "BH", "BHT", "BIH", "BOL", "BR", "BRN", "BRU", "BS", "BU", "BW", "BY", "C", "CU", "CAM", "CDN", "CGO", "CH", "CHN", "CI", "CL", "CO", "COM", "CR", "CV", "CY", "CZ", "D", "DJI", "DK", "DOM", "DY", "DZ", "E", "EAK", "EAZ", "EAU", "EC", "ERI", "ES", "EST", "ET", "ETH", "F", "FIN", "FJI", "FL", "FSM", "G", "GCA", "GE", "GH", "GR", "GUB", "GUI", "GUY", "H", "HKJ", "HN", "HR", "I", "IL", "IND", "IR", "IRL", "IRQ", "IS", "J", "JA", "K", "KIG", "KIR", "KN", "KP", "KS", "KSA", "KWT", "KZ", "L", "LAO", "LAR", "LB", "LS", "LT", "LV", "M", "MA", "MAL", "MC", "MD", "MEX", "MGL", "MNE", "MNS", "MOZ", "MS", "MW", "MYA", "N", "NAM", "NAU", "NIC", "NL", "NMK", "NZ", "OM", "P", "PA", "PE", "PK", "PL", "PRI", "PY", "QA", "RA", "RC", "RCA", "RCB", "RCH", "RG", "RH", "RI", "RIM", "RKS", "RL", "RM", "RMM", "RN", "RO", "ROK", "ROU", "RP", "RSM", "RT", "RUS", "RWA", "S", "SA", "SCN", "SCV", "SD", "SGP", "SK", "SLB", "SLO", "SME", "SN", "SO", "SOL", "SRB", "STP", "SY", "SYR", "T", "TJ", "TL", "TM", "TN", "TR", "TT", "TUV", "UA", "UAE", "UK", "USA", "UZ", "VN", "WAG", "WAL", "WAN", "WD", "WG", "WL", "WS", "WV", "Y", "YV", "Z", "ZA", "ZW" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(autor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date)
                .addGap(179, 179, 179)
                .addComponent(logo)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kraj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IdB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(250, 250, 250))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kraj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autor)
                            .addComponent(date))
                        .addGap(15, 15, 15)))
                .addGap(15, 15, 15))
        );

        generate.setBorderPainted(false);
        generate.setFocusPainted(false);
        generate.setRolloverEnabled(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdBActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        MainWindow mw = new MainWindow();
        mw.show();

        dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseExited
        back1.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_back1MouseExited

    private void back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseEntered
        back1.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_back1MouseEntered

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        try {
            //STEROWNIK POŁĄCZENIA
            Class.forName("org.firebirdsql.jdbc.FBDriver");
            //SPRAWDZENIE POŁĄCZENIA Z BAZĄ
            try (Connection con = DriverManager.getConnection("jdbc:firebirdsql://localhost:3050//databases/skp.fdb", "SYSDBA", "Czarek08#")) {
                String reportPath = "/databases/Raporty/Zaswiadczenie.jrxml";
                int Id_b = Integer.parseInt(IdB.getSelectedItem().toString());

                //GENEROWANIE IDENTYFIKATORA (KODU) RAPORTU
                String znaki = "abcdefghijklmnopqrstuvwxyz1234567890";
                StringBuilder kodID = new StringBuilder();
                Random random = new Random();
                for (int i = 0; i < 19; i++) {
                    if (i == 4 || i == 9 || i == 14) {
                        kodID.append("-");
                    } else {
                        kodID.append(znaki.charAt(random.nextInt(znaki.length())));
                    }
                }
                
                overviewType(Id_b);

                //PARAMETRY
                HashMap<String, Object> parametry = new HashMap<String, Object>();
                parametry.put("Id_badania", Id_b);
                parametry.put("Typ_badania", TypB);
                parametry.put("kraj", kraj.getSelectedItem().toString());

                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                JasperPrint jp = JasperFillManager.fillReport(jr, parametry, con);
                JasperViewer.viewReport(jp, false);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_generateActionPerformed

    private void generateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseExited
        generate.setBackground(new Color(54, 88, 150));
    }//GEN-LAST:event_generateMouseExited

    private void generateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseEntered
        generate.setBackground(new Color(135,162,212));
    }//GEN-LAST:event_generateMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Raport6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IdB;
    private javax.swing.JLabel autor;
    private javax.swing.JButton back1;
    private javax.swing.JLabel date;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> kraj;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel tytul;
    private javax.swing.JLabel tytul1;
    // End of variables declaration//GEN-END:variables
}
